// pdf-generator — generate HTML documents from markdown and upload to Storage.
// -----------------------------------------------------------------------------
// Accepts POST { title, body_markdown, doc_type, locale, case_id? }
// Converts markdown to HTML, uploads to case-documents bucket, creates a
// signed URL, optionally inserts a case_documents row, and returns:
//   { download_url, storage_path, filename, document_id }
//
// Auth: user JWT only (no anonymous). Rate limit: 2/min per user.
// Storage: service-role client uploads to {user_id}/generated/{slug}_{ts}.html
// DB: if case_id is provided, a row is inserted into case_documents.
// -----------------------------------------------------------------------------

import { serve } from "https://deno.land/std@0.177.0/http/server.ts";
import {
  corsHeaders,
  jsonError,
  jsonOk,
  requireUserWithRateLimit,
} from "../_shared/auth.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

const STORAGE_BUCKET = "case-documents";
/** Signed URL validity — 1 hour. */
const SIGNED_URL_EXPIRES_IN = 3600;

// =============================================================================
// HTML template
// =============================================================================

const HTML_TEMPLATE = `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
<style>
body { font-family: Georgia, serif; font-size: 12pt; margin: 2.5cm; line-height: 1.6; color: #111; }
h1 { font-size: 16pt; text-align: center; margin-bottom: 1cm; }
h2 { font-size: 13pt; border-bottom: 1px solid #ccc; padding-bottom: 4px; margin-top: 1cm; }
p { text-align: justify; margin: 0.4cm 0; }
ul { margin: 0.3cm 0 0.3cm 1cm; }
.footer { margin-top: 2cm; font-size: 9pt; color: #888; border-top: 1px solid #eee; padding-top: 0.5cm; }
</style>
</head>
<body>
<h1>{{TITLE}}</h1>
{{BODY}}
<div class="footer">Generated by Advocat.ee · {{DATE}}</div>
</body>
</html>`;

// =============================================================================
// Markdown → HTML conversion (simple regex, no external deps)
// =============================================================================

/**
 * Converts a limited subset of Markdown to HTML:
 *   ## heading  → <h2>
 *   # heading   → <h1> (only when the title param doesn't already cover h1)
 *   **bold**    → <strong>
 *   *italic*    → <em>
 *   - item      → <ul><li>…</li></ul>
 *   blank line  → paragraph break
 */
export function markdownToHtml(md: string): string {
  // Normalise line endings.
  const lines = md.replace(/\r\n/g, "\n").replace(/\r/g, "\n").split("\n");

  const out: string[] = [];
  let inList = false;

  for (let raw of lines) {
    // Heading level 2
    if (/^## /.test(raw)) {
      if (inList) { out.push("</ul>"); inList = false; }
      const text = inlineMarkdown(raw.slice(3).trim());
      out.push(`<h2>${text}</h2>`);
      continue;
    }
    // Heading level 1 (inside body — becomes h2 visually to avoid clashing
    // with the document title h1 at the top of the template)
    if (/^# /.test(raw)) {
      if (inList) { out.push("</ul>"); inList = false; }
      const text = inlineMarkdown(raw.slice(2).trim());
      out.push(`<h2>${text}</h2>`);
      continue;
    }
    // List item
    if (/^- /.test(raw)) {
      if (!inList) { out.push("<ul>"); inList = true; }
      const text = inlineMarkdown(raw.slice(2).trim());
      out.push(`<li>${text}</li>`);
      continue;
    }
    // Blank line — close list or end paragraph
    if (raw.trim() === "") {
      if (inList) { out.push("</ul>"); inList = false; }
      // A blank line is a paragraph separator; we push a sentinel that gets
      // collapsed with surrounding content into a <p> below.
      out.push("__BLANK__");
      continue;
    }
    // Normal text line — close list if open
    if (inList) { out.push("</ul>"); inList = false; }
    out.push(inlineMarkdown(raw.trim()));
  }
  if (inList) out.push("</ul>");

  // Group consecutive non-special lines into <p> tags.
  const result: string[] = [];
  let paragraphLines: string[] = [];

  const flushParagraph = () => {
    if (paragraphLines.length > 0) {
      result.push(`<p>${paragraphLines.join(" ")}</p>`);
      paragraphLines = [];
    }
  };

  for (const line of out) {
    if (line.startsWith("<h") || line.startsWith("<ul") || line.startsWith("</ul") || line.startsWith("<li")) {
      flushParagraph();
      result.push(line);
    } else if (line === "__BLANK__") {
      flushParagraph();
    } else {
      paragraphLines.push(line);
    }
  }
  flushParagraph();

  return result.join("\n");
}

/** Apply inline markdown (bold, italic) to a single text run. */
function inlineMarkdown(text: string): string {
  // SECURITY: body_markdown is user/LLM-controlled and the rendered output is
  // stored as text/html and served via a signed URL — raw `<script>` / event
  // handlers would execute on open (stored XSS). Escape HTML entities FIRST,
  // then apply our own markdown→tag transforms. Because escapeHtml turns any
  // user `<`/`>`/`&` into entities, the only literal `<…>` tags in the result
  // are the <strong>/<em> we emit ourselves below.
  const escaped = escapeHtml(text);
  // Bold before italic so **bold** is processed first.
  return escaped
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/\*([^*]+)\*/g, "<em>$1</em>");
}

// =============================================================================
// Filename sanitiser
// =============================================================================

/** Convert a title to a safe ASCII filename slug. */
export function sanitiseTitle(title: string): string {
  return title
    .toLowerCase()
    .replace(/[äåàáâãæ]/g, "a")
    .replace(/[öøòóôõ]/g, "o")
    .replace(/[üùúû]/g, "u")
    .replace(/[ìíîï]/g, "i")
    .replace(/[èéêë]/g, "e")
    .replace(/[ñ]/g, "n")
    .replace(/[ç]/g, "c")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 60) || "document";
}

// =============================================================================
// Request validation
// =============================================================================

interface RequestBody {
  title: string;
  body_markdown: string;
  doc_type: string;
  locale: string;
  case_id?: string | null;
}

function parseBody(raw: unknown, userId: string): RequestBody {
  if (!raw || typeof raw !== "object") throw new Error("Request body must be a JSON object");
  const b = raw as Record<string, unknown>;

  const title = typeof b.title === "string" ? b.title.trim() : "";
  if (!title) throw new Error("title is required");
  if (title.length > 200) throw new Error("title must be ≤200 characters");

  const bodyMarkdown = typeof b.body_markdown === "string" ? b.body_markdown : "";
  if (!bodyMarkdown.trim()) throw new Error("body_markdown is required");
  if (bodyMarkdown.length > 100_000) throw new Error("body_markdown must be ≤100 000 characters");

  const docType = typeof b.doc_type === "string" ? b.doc_type.trim() : "other";
  const locale = typeof b.locale === "string" ? b.locale.trim().slice(0, 10) : "en";

  const caseId = typeof b.case_id === "string" && b.case_id.trim()
    ? b.case_id.trim()
    : null;

  // Enforce storage path prefix ownership: case_id must be a UUID if provided.
  // (We check user ownership implicitly via the {user_id}/... path prefix.)
  if (caseId && !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(caseId)) {
    throw new Error("case_id must be a valid UUID");
  }

  // Validate user_id is a UUID (should always be, but guard anyway).
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(userId)) {
    throw new Error("Invalid user session");
  }

  return { title, body_markdown: bodyMarkdown, doc_type: docType, locale, case_id: caseId };
}

// =============================================================================
// Storage upload via Supabase REST API
// =============================================================================

/**
 * Upload bytes to Supabase Storage using the REST API and service-role key.
 * Returns the storage_path on success or throws.
 */
async function uploadToStorage(
  storagePath: string,
  content: Uint8Array,
  contentType: string,
): Promise<void> {
  const url = `${SUPABASE_URL}/storage/v1/object/${STORAGE_BUCKET}/${storagePath}`;
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,
      "apikey": SUPABASE_SERVICE_ROLE_KEY,
      "Content-Type": contentType,
      "x-upsert": "true",
    },
    // After the Deno typing upgrade, `Uint8Array<ArrayBufferLike>` is no
    // longer directly assignable to BodyInit (the new lib.dom.d.ts wants
    // `Uint8Array<ArrayBuffer>` — strict ArrayBuffer, not SharedArrayBuffer).
    // Wrap in a Blob via a typed BlobPart cast — same wire bytes, satisfies
    // the BodyInit overload. The runtime is unchanged.
    body: new Blob([content as BlobPart], { type: contentType }),
  });
  if (!res.ok) {
    const snippet = (await res.text()).slice(0, 300);
    throw new Error(`Storage upload failed (${res.status}): ${snippet}`);
  }
}

/**
 * Create a signed URL for an object in the case-documents bucket.
 * Returns the signed URL string or throws.
 */
async function createSignedUrl(storagePath: string): Promise<string> {
  const url = `${SUPABASE_URL}/storage/v1/object/sign/${STORAGE_BUCKET}/${storagePath}`;
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,
      "apikey": SUPABASE_SERVICE_ROLE_KEY,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ expiresIn: SIGNED_URL_EXPIRES_IN }),
  });
  if (!res.ok) {
    const snippet = (await res.text()).slice(0, 300);
    throw new Error(`Signed URL creation failed (${res.status}): ${snippet}`);
  }
  const json = await res.json() as { signedURL?: string; signedUrl?: string };
  const signed = json.signedURL ?? json.signedUrl ?? "";
  if (!signed) throw new Error("Signed URL response missing signedURL field");
  // Supabase returns a path like /storage/v1/object/sign/... — prefix base URL.
  if (signed.startsWith("/")) return `${SUPABASE_URL}${signed}`;
  return signed;
}

// =============================================================================
// case_documents row insert
// =============================================================================

/**
 * Insert a minimal row into case_documents so the generated file appears in
 * the case vault. Returns the new row id or null on failure (non-fatal).
 */
async function insertCaseDocument(
  userId: string,
  caseId: string,
  filename: string,
  storagePath: string,
  docType: string,
  title: string,
): Promise<string | null> {
  const url = `${SUPABASE_URL}/rest/v1/case_documents`;
  const body = {
    case_id: caseId,
    user_id: userId,
    filename,
    storage_path: storagePath,
    mime_type: "text/html",
    size_bytes: 0, // approximate; exact size not critical for generated docs
    doc_type: docType,
    parsed_summary: title,
    parsed_text: "",
    key_extractions: [],
    embedding: null,
  };
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,
      "apikey": SUPABASE_SERVICE_ROLE_KEY,
      "Content-Type": "application/json",
      "Prefer": "return=representation",
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const snippet = (await res.text()).slice(0, 300);
    console.warn(`pdf-generator: case_documents insert failed (${res.status}): ${snippet}`);
    return null;
  }
  const rows = await res.json() as Array<{ id?: string }>;
  return rows[0]?.id ?? null;
}

// =============================================================================
// HTTP entry point
// =============================================================================

serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: corsHeaders });
  }
  if (req.method !== "POST") {
    return jsonError("Method not allowed", 405);
  }

  // ── 1. Auth + rate-limit (2/min — document generation is expensive). ───
  const gate = await requireUserWithRateLimit(req, {
    bucket: "pdf-generator",
    maxPerMinute: 2,
  });
  if (gate.kind === "deny") return gate.response;
  const userId = gate.user.id;

  // ── 2. Parse + validate body. ─────────────────────────────────────────
  let body: RequestBody;
  try {
    body = parseBody(await req.json(), userId);
  } catch (e) {
    return jsonError(String(e instanceof Error ? e.message : e), 400);
  }

  // ── 3. Render Markdown → HTML. ────────────────────────────────────────
  const bodyHtml = markdownToHtml(body.body_markdown);
  const dateStr = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

  const html = HTML_TEMPLATE
    .replace("{{TITLE}}", escapeHtml(body.title))
    .replace("{{BODY}}", bodyHtml)
    .replace("{{DATE}}", dateStr);

  const encoder = new TextEncoder();
  const htmlBytes = encoder.encode(html);

  // ── 4. Upload to Storage. ─────────────────────────────────────────────
  const slug = sanitiseTitle(body.title);
  const ts = Date.now();
  const filename = `${slug}_${ts}.html`;
  const storagePath = `${userId}/generated/${filename}`;

  try {
    await uploadToStorage(storagePath, htmlBytes, "text/html");
  } catch (e) {
    console.error(`pdf-generator: upload failed: ${String(e).slice(0, 300)}`);
    return jsonError("Failed to upload generated document", 502);
  }

  // ── 5. Create signed URL (1 hour). ────────────────────────────────────
  let downloadUrl: string;
  try {
    downloadUrl = await createSignedUrl(storagePath);
  } catch (e) {
    console.error(`pdf-generator: signed URL failed: ${String(e).slice(0, 300)}`);
    return jsonError("Failed to create download link", 502);
  }

  // ── 6. Insert case_documents row if case_id was provided. ─────────────
  let documentId: string | null = null;
  if (body.case_id) {
    documentId = await insertCaseDocument(
      userId,
      body.case_id,
      filename,
      storagePath,
      body.doc_type,
      body.title,
    );
  }

  return jsonOk({
    download_url: downloadUrl,
    storage_path: storagePath,
    filename,
    document_id: documentId,
  });
});

// =============================================================================
// Helpers
// =============================================================================

/** Minimal HTML entity escaping for the document title. */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
